### ISSUE TITLE
Class Not Found 

### ISSUE THREAD

**Issue by N1ourS1ouid** [dpa99c/cordova-plugin-hello-c#11] opened 2019-04-17 09:22 UTC
I downloaded the plugin and run it on the test project. However, when I run it on my emulator I had class not found ! (and I hadn't changed the C code yet!) 
android version: 8.0.0
Cordova version: 9.0.0 (cordova-lib@9.0.1)
![Capture](https://user-images.githubusercontent.com/49376370/56275940-9259e980-60f9-11e9-8706-6ba4d284ce58.PNG)

**Comment by dpa99c** [comment] 2019-04-17 13:01
Duplicate of #10.

See https://github.com/apache/cordova-android/issues/683

**Closed as completed by dpa99c** 2019-04-17 13:01 UTC
